server {
    listen 80;
    server_name geovise.io 159.223.122.52 localhost;
    root /var/www/geovise;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Optional: Cache control for static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
